# Generated by Django 4.2.3 on 2023-07-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_dateexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
